import { ReactQueryProvider } from "./ReactQueryProvider";
import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Create Next App",
	description: "Generated by create next apgp",
};

export default function RootLayout({
	children,
	modal,
}: {
	modal: React.ReactNode;
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<ReactQueryProvider>
				<body className={inter.className}>
					{children}
					{modal}
				</body>
			</ReactQueryProvider>
		</html>
	);
}
